name: Release Please

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
      upload_url: ${{ steps.release_please.outputs.upload_url }}
      tag_name: ${{ steps.release_please.outputs.tag_name }}
      name: ${{ steps.release_please.outputs.name }}
      body: ${{ steps.release_please.outputs.body }}
      draft: ${{ steps.release_please.outputs.draft }}
      prerelease: ${{ steps.release_please.outputs.prerelease }}

    steps:
    - uses: googleapis/release-please-action@v4
      id: release_please
      with:
        release-type: go
        path: .
        token: ${{ secrets.GITHUB_TOKEN }}
